## docker-compose.yml
version: '3'
services:
  hddtemp:
    container_name: hddtemp
    image: emilgil/hddtemp:latest
    restart: always
    privileged: true
    ports:
      - 7634:7634
    environment:
      - DRIVES=sd[abcde]
